export const SET_IS_BLOCK_EDITOR_PAGE = 'SET_IS_BLOCK_EDITOR_PAGE';
export const SET_IS_WOOCOMMERCE_PRODUCT_PAGE =
	'SET_IS_WOOCOMMERCE_PRODUCT_PAGE';
export const SET_STATUS = 'SET_STATUS';
export const SET_MESSAGE = 'SET_MESSAGE';
export const SET_GENERATED_URL = 'SET_GENERATED_URL';
export const SET_ERROR = 'SET_ERROR';
export const SET_UPLOADING = 'SET_UPLOADING';
export const SET_IMAGE_CONFIG_DATA = 'SET_IMAGE_CONFIG_DATA';
export const SET_SELECTED_IMAGE_INDICES = 'SET_SELECTED_IMAGE_INDICES';
export const SET_ACTIVE_TAB = 'SET_ACTIVE_TAB';
export const SET_IS_THUMBNAIL_MODE = 'SET_IS_THUMBNAIL_MODE';
export const SET_IMAGE_URLS = 'SET_IMAGE_URLS';
export const SET_ATTACHMENT_IDS = 'SET_ATTACHMENT_IDS';
export const SET_SUPPORTS_VIDEO = 'SET_SUPPORTS_VIDEO';
export const RESET_STATE = 'RESET_STATE';
